### ISSUE TITLE
always_run is deprecated

### ISSUE THREAD

**Issue by KubaRocks** [geerlingguy/ansible-role-mas#1]
```
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4.
```
This is what I get on `Ansible 2.2.0.0`

**Comment by geerlingguy** [comment]
Unfortunately, Ansible doesn't leave me a lot of wiggle room here—if I switch to `check_mode`, then the role breaks for everyone on Ansible < 2.2.0 (which is still a lot of people). So I'm going to leave it until 2.3.0 is out.

**Comment by geerlingguy** [comment]
2.2.1 is here, the deprecation notice is still here... still waiting until 2.3.

**Comment by geerlingguy** [comment]
2.3.0-rc1 is out... getting closer!

**Comment by mvanbaak** [comment]
Ansible 2.3.1 is the latest version (checked right now).

**Comment by geerlingguy** [comment]
Ah yes, time to fix it :)

**Comment by geerlingguy** [comment]
Oh, this was fixed already — see https://github.com/geerlingguy/ansible-role-mas/blob/master/tasks/main.yml#L24 (updated in https://github.com/geerlingguy/ansible-role-mas/commit/7d6f40b66b2b00f0ca3f68c6929a54433d24f956)
