### ISSUE TITLE
"Get MAS account status" fails, mas command not found

### ISSUE THREAD

**Issue by jklaiho** [geerlingguy/ansible-role-mas#18]
I'm building a playbook for setting up some headless Mac Mini build servers at the office. It is run from my workstation over SSH to each build server simultaneously, rather than locally on each individually.

The first task in this role, "Ensure MAS is installed", works just fine (the `mas` command is indeed present on the servers afterwards, if I go and check). But "Get MAS account status" fails like so:

`FAILED! => {"changed": false, "cmd": "mas account", "failed_when_result": true, "msg": "[Errno 2] No such file or directory", "rc": 2}`

This looks like a path issue. `mas` is present in `/usr/local/bin`. `/usr/local/bin` is in `/etc/paths` and also present in the `$PATH` variable for the user who I'm connecting over SSH with, when I'm in the interactive shell of the target server.

However, it seems that Ansible is using a different path that doesn't include `/usr/local/bin`. Doing `- debug: msg="{{ ansible_env.PATH }}"`, the result is `/usr/bin:/bin:/usr/sbin:/sbin`.

I think it would be nice if this role had the full path to the `mas` executable in the tasks so that it wouldn't rely on Ansible's PATH determination logic.

Since `mas` is installed via Homebrew, perhaps you could introduce the following defaults from geerlingguy/ansible-role-homebrew into this role as well:

```
homebrew_prefix: /usr/local
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"
```

...and then have the task look like this:

`command: "{{ homebrew_brew_bin_path }}/mas account"`

As far as I can tell, this should work both for homebrew installed via geerlingguy.homebrew and homebrew installed via other means, allowing the user to set a custom homebrew path in both cases.

An alternative method is to document this environment trick in the playbook (seems to work globally, per role or per task):

```
- role: geerlingguy.mas
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
```

This is what I'm using currently, but I feel like this issue would be better handled at the role level rather than requiring every user of the role to alter the environment at the playbook level.

**Comment by lilithlavender** [comment]
I'm having this exact same issue setting up some Mac Minis. Your `environment` workaround worked perfectly.

**Comment by moltar** [comment]
If this indeed is added to the role, then the correct way to read the brew dir is probably do a task that registers output from `brew --prefix` and then uses that in the task itself.

**Comment by bboles** [comment]
This issue still persists.  Worked around it by using the `environment` hack.
