### ISSUE TITLE
deprecated bare variable use

### ISSUE THREAD

**Issue by moltar** [geerlingguy/ansible-role-mas#21]
Getting the following warning:

```
[DEPRECATION WARNING]: evaluating [{'id': 123, 'name': 'Foo'}] as a
bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see
CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
```

**Comment by geerlingguy** [comment]
@moltar - Using the latest version of the role, at least in CI, I'm not seeing the bare deprecation warning like you see (see: https://travis-ci.org/geerlingguy/ansible-role-mas/jobs/654470512).

Can you provide a little more context? Which task did you see this on?

**Comment by geerlingguy** [comment]
Closing as I don't see anywhere it seems to be present in the latest version of the role. Please post back if you can provide more context for where this deprecation warning appeared.

**Comment by lukasleitsch** [comment]
I saw the same deprecation warning.

```
TASK [geerlingguy.mas : Ensure MAS is installed.] *********************************************************************************************
[DEPRECATION WARNING]: evaluating 'mas_installed_apps' as a bare variable, this behaviour will go away and you might need to add |bool to the 
expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. This feature will be removed in version 2.12. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

- ansible 2.9.11
- latest version of your role

Calling the role like in your playbook: https://github.com/geerlingguy/mac-dev-playbook/blob/master/main.yml#L20

Use `when: mas_installed_apps|length > 0` ensures to get rid of the deprecation message. 

```
  roles:
    - role: geerlingguy.mas
      when: mas_installed_apps|length > 0
      tags:
        - mas
```
