### ISSUE TITLE
async install

### ISSUE THREAD

**Issue by icwr** [geerlingguy/ansible-role-mas#29]
Hi, thanks for all the work on this. I was able to successfully install apps with this role but I've noticed with some huge apps (such as xcode) this task can run for a really long time depending on connection speed. Eventually, once the installation completes the play stops with a connection error: `Failed to connect to the host via ssh .... Operation timed out`. 

Would it be possible to add async and poll to the _Ensure configured MAS apps are installed_ task? Or, is there another way I can setup my playbook/tasks to avoid the connection issue? Thanks

**Comment by geerlingguy** [comment]
Yeah... it would be nice to make it so something like Xcode doesn't break the setup—it took like 1 hour on my new M1 MacBook Air!

**Comment by geerlingguy** [comment]
Closing all issues in this repository in preparation for a migration to `geerlingguy.mac`—see https://github.com/geerlingguy/ansible-role-mas/issues/31
