### ISSUE TITLE
mas install over ssh

### ISSUE THREAD

**Issue by Squallium** [geerlingguy/ansible-role-mas#7]
Hi,

I'm trying to install apps through ssh and I encountered a problem in mas cli project. Only if I use sudo the app is installed, I don't know if I'm doing anything wrong but putting "become: true" in every task except the homebrew one solved the problem.

I don't know if this is the correct communication channel but I can't see any email in your info to contact you directly.

Thanks in advanced and sorry for the inconveniences.

**Comment by geerlingguy** [comment]
@Squallium - No problem! This role is tested without using `sudo`/`become`, and should work in that way. But maybe there are some things you're doing in your playbook that require elevated privileges?

**Comment by Squallium** [comment]
Hi, 
Thank you for answer me! I tested you example locally and It works, but with ssh from other computer the process freeze in "Ensure configured MAS apps are installed" task.
Then I try directly with the mas cli, and again locally works but using ssh from other machine I need to run the command as sudo. I'm using macOS Sierra 10.12.3 I don't know if this is important.

Thank you again for your time.

**Comment by geerlingguy** [comment]
Interesting, maybe it's something in the `mas` cli that assumes it's being run locally/interactively. I haven't tried using `mas` on a remote computer yet, but may try later to see if I can reproduce the error with and without Ansible.

**Comment by mindrunner** [comment]
Any news on this? I can comfirm, that install task freezes when running ansible via ssh.

**Comment by geerlingguy** [comment]
I haven't had time to work on this, no. But I'd be able to review and merge a patch if someone else can find out what's happening.

**Comment by mindrunner** [comment]
I might have a working fix. At least it solved my problems here and I can install MAS apps. Will come along with a PR next week!

**Comment by mindrunner** [comment]
So, here I am again. I copied the mas-role to a local one and changed all calls to "become: true", so that mas is run as root. With that change the here discussed problem is solved/workedaround. 

Furthermore, I commented out the "mas list" part, because of https://github.com/mas-cli/mas/issues/82

Is that suitable for a PR, or do we have to discuss this before?

**Comment by daften** [comment]
Is it an option to only run mas stuff on ansible_connection == "local" and put this in documentation ?

**Comment by elliotweiser** [comment]
@daften My current (untested) theory is that remote/SSH connections can be used for MAS if `sshd` is running as a "LaunchAgent" and not a "LaunchDaemon". I was investigating that myself a year-or-so back, so my information may be somewhat dated. I'll see if I can verify that when I get a few spare cycles.

**Comment by daften** [comment]
@elliotweiser were you able to check this?

**Comment by khaosx** [comment]
I can verify that mas install doesn't work via SSH if running as a Daemon. All other commands work as expected, including mas account, but mas install hangs for as long as I have patience to watch it. Sudo mas install ID_OF_APP returns "not signed in". Hope this helps!

**Comment by mike-pt** [comment]
Just bumped into this, any idea why it happens?

**Comment by sjames-au** [comment]
I finally hit this problem as well.

Reviewing the mas-cli repo, it appears that this is related to mas and how it interacts with the AppStore to do its magic.

https://github.com/mas-cli/mas/issues/128#issuecomment-478419530
