### ISSUE TITLE
"when statements should not include jinja2 templating delimiters"

### ISSUE THREAD

**Issue by RotsiserMho** [geerlingguy/ansible-role-mas#9]
I'm using Ansible 2.3.1.0 and I encountered this warning:

> TASK [ansible-role-mas : Ensure configured MAS apps are installed.] ****************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: '{{ item.id|default(item) }}' not in mas_list.stdout

**Comment by stalinkay** [comment]
+1 @geerlingguy

**Comment by Anima-t3d** [comment]
Same here.

**Comment by nikolai-derzhak-distillery** [comment]
The same here: https://github.com/geerlingguy/ansible-role-nfs/issues/23
